config/routes.rb
Rails.application.routes.draw do
  resources :puzzles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_action :set_puzzle, only: [:show, :edit, :update, :destroy]

  # GET /puzzles
  # GET /puzzles.json
  def index
    @puzzles = Puzzle.all
  end

  # GET /puzzles/1
  # GET /puzzles/1.json
  def show
    @puzzle = Puzzle.find_by(id: params[:id])
  end

  # GET /puzzles/new
  def new
    @puzzle = Puzzle.new
  end

  # GET /puzzles/1/edit
  def edit
  end

  # POST /puzzles
  # POST /puzzles.json
  def create
    @puzzle = Puzzle.new(puzzle_params)

    respond_to do |format|
      if @puzzle.save
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully created.' }
        format.json { render :show, status: :created, location: @puzzle }
      else
        format.html { render :new }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puzzles/1
  # PATCH/PUT /puzzles/1.json
  def update
    respond_to do |format|
      if @puzzle.update(puzzle_params)
        format.html { redirect_to @puzzle, notice: 'Puzzle was successfully updated.' }
        format.json { render :show, status: :ok, location: @puzzle }
      else
        format.html { render :edit }
        format.json { render json: @puzzle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puzzles/1
  # DELETE /puzzles/1.json
  def destroy
    @puzzle.destroy
    respond_to do |format|
      format.html { redirect_to puzzles_url, notice: 'Puzzle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puzzle
      @puzzle = Puzzle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puzzle_params
      params.require(:puzzle).permit(:img_url1, :img_url2, :img_url3, :phrase)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThreeThings</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/puzzles/_form.html.erb
<%= form_with(model: puzzle, local: true) do |form| %>
  <% if puzzle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(puzzle.errors.count, "error") %> prohibited this puzzle from being saved:</h2>

      <ul>
      <% puzzle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form_for :puzzle do |f| %>
  img_url1: <%= f.text_field :img_url1 %><br />
  img_url2: <%= f.text_field :img_url2 %><br />
  img_url3: <%= f.text_field :img_url3 %><br />
  phrase: <%= f.text_field :phrase %><br />
  <%= f.submit %>
<% end %>
  </div>
<% end %>

app/views/puzzles/edit.html.erb
<h1>Editing Puzzle</h1>

<%= render 'form', puzzle: @puzzle %>

<%= link_to 'Show', @puzzle %> |
<%= link_to 'Back', puzzles_path %>

app/views/puzzles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Puzzles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puzzles.each do |puzzle| %>
      <tr>
        <td><%= puzzle.phrase %></td>
        <td><%= link_to 'Show', puzzle %></td>
        <td><%= link_to 'Edit', edit_puzzle_path(puzzle) %></td>
        <td><%= link_to 'Destroy', puzzle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puzzle', new_puzzle_path %>

app/views/puzzles/new.html.erb
<h1>New Puzzle</h1>

<%= render 'form', puzzle: @puzzle %>

<%= link_to 'Back', puzzles_path %>

app/views/puzzles/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<p id="notice"><%= notice %></p>








<div class="w3-container w3-green">
  <h1><%= @puzzle.phrase %><br></h1>
  <p>Resize this responsive page!</p>
</div>

<div class="w3-row-padding">
  <div class="w3-third">
    <h2>London</h2>
    <div style="width:100%;height:0;padding-bottom:75%;position:relative;"><iframe src="https://giphy.com/embed/JXHhI4o9NCf8k" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p>
    <%= @puzzle.img_url1 %><br>
  </div>

  <div class="w3-third">
    <h2>Paris</h2>
<div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/cHGJwA8aO8epq" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>
<%= @puzzle.img_url2 %><br>
  </div>

  <div class="w3-third">
    <h2>Tokyo</h2>
    <div style="width:100%;height:0;padding-bottom:56%;position:relative;"><iframe src="https://giphy.com/embed/l0MYAMG9uhRUyh7zi" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div>

    <%= @puzzle.img_url3 %><br>
  </div>
</div>




<%= link_to 'Edit', edit_puzzle_path(@puzzle) %> |
<%= link_to 'Back', puzzles_path %>